### ISSUE TITLE
请问如何基于 metapath 进行采样？

### ISSUE THREAD

**Issue by ethan-funny** [Tencent/embedx#1]
感谢开源 EmbedX。

我的问题如下：

在异构图模型中，我们经常会基于 元路径 (metapath) 进行采样，比如 author-paper-conference 。

看了相关的示例和代码，没有找到如何基于 metapath 进行采样，请问是否可以写个示例 run_metapth2vec.sh ?

谢谢！

**Comment by longsail** [comment]
基于metapath的采样之前代码是有的，没考虑好在代码层面如何将metapath与node2vec的优化一起实现，暂时删掉了。

**Comment by ethan-funny** [comment]
好的，期待。

**Comment by longsail** [comment]
本周内部讨论下，如果分开实现，可以很快提供出来

**Comment by longsail** [comment]
> 

本周提供出来

**Comment by longsail** [comment]
> 好的，期待。

本周实现，提供出来

**Comment by longsail** [comment]
已经支持
