### ISSUE TITLE
请教如何部署embedx分布式环境

### ISSUE THREAD

**Issue by liaoyubinAI** [Tencent/embedx#3]
首先感谢微信大佬开源那么牛掰的工具。在我们业务上单机实现deepwalk并取得正向效果，速度快得飞起，赞。受限于单机资源问题。请教大佬是否可以提供详细的embedx分布式部署教程。非常感谢。

**Comment by longsail** [comment]
> 首先感谢微信大佬开源那么牛掰的工具。在我们业务上单机实现deepwalk并取得正向效果，速度快得飞起，赞。受限于单机资源问题。请教大佬是否可以提供详细的embedx分布式部署教程。非常感谢。

目前的分布式脚本，是否可以改造使用？
